FROM php:8.2-cli

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev && docker-php-ext-install curl

EXPOSE 10000

CMD ["php", "-S", "0.0.0.0:10000", "index.php"]
